### ISSUE TITLE
computeLinkBudget should return a scalar

### ISSUE THREAD

**Issue by artuso0matteo** [Sonohi/monster#87] opened 2019-02-21 12:02 UTC
The bug happens when setting 1 eNodeB per type and setting the MacroEnb.radius to 500

**Comment by jakthra** [comment] 2019-02-21 13:56
computeLinkBudget complains, but in reality this is `loss3gpp38901` that returns a vector. It should return a scalar.

**Comment by MonsterMarkus** [comment] 2019-02-21 14:02
I am unable to reproduce the error. I have set 1 of each eNodeB type and the radius to 500, but the error does not appear.

**Comment by jakthra** [comment] 2019-02-21 14:26
Fixed in pull request #88

**Closed by jakthra** 2019-02-21 14:26 UTC
Labels: bug
